spring:
  application:
    name: novare-service
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:    
    hibernate:
      ddl-auto: update
    #open-in-view: true
    #show-sql: true
    # properties:
    #   hibernate:
    #     format_sql: true

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'


novare-service:
  page: 0
  size: 2



  

  

    

