spring:
  datasource:
    url: jdbc:mysql://192.168.200.11:3306/test #${DATASOURCE_URL}
    username: root #${DATASOURCE_USERNAME}
    password: cbb@1985 #${DATASOURCE_PASSWORD}

  jpa:    
    hibernate:
      ddl-auto: update
    #open-in-view: true
    #show-sql: true
    # properties:
    #   hibernate:
    #     format_sql: true


  

  

    

