spring:
  application:
    name: novare-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      profile: prod
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:    
    hibernate:
      ddl-auto: update
    #open-in-view: true
    #show-sql: true
    # properties:
    #   hibernate:
    #     format_sql: true
  
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'



  

  

    

