server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gagjunior/java-config-server
          default-label: main
          search-paths:
          - 'config-service*'
          #username: 
          #password:

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'


  

  

    

